// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB6sjbYbXrUgaS_gH6R9RdXXzUAKPFn-M',
    appId: '1:668620879848:web:a0d936e37db90773cdd65d',
    messagingSenderId: '668620879848',
    projectId: 'chat-app-f57d1',
    authDomain: 'chat-app-f57d1.firebaseapp.com',
    storageBucket: 'chat-app-f57d1.firebasestorage.app',
    measurementId: 'G-9F15GCPKXH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsQQhI97B_XJADFvJXuWOFyR0YV63_n4g',
    appId: '1:668620879848:android:4f408e9bf0de4211cdd65d',
    messagingSenderId: '668620879848',
    projectId: 'chat-app-f57d1',
    storageBucket: 'chat-app-f57d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAIRlvEoMfuj-CtZSBVDdAaIuWR-zeNUk',
    appId: '1:668620879848:ios:cdb52e8a37b19ba6cdd65d',
    messagingSenderId: '668620879848',
    projectId: 'chat-app-f57d1',
    storageBucket: 'chat-app-f57d1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAIRlvEoMfuj-CtZSBVDdAaIuWR-zeNUk',
    appId: '1:668620879848:ios:cdb52e8a37b19ba6cdd65d',
    messagingSenderId: '668620879848',
    projectId: 'chat-app-f57d1',
    storageBucket: 'chat-app-f57d1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBB6sjbYbXrUgaS_gH6R9RdXXzUAKPFn-M',
    appId: '1:668620879848:web:ebb6ceca5f89de35cdd65d',
    messagingSenderId: '668620879848',
    projectId: 'chat-app-f57d1',
    authDomain: 'chat-app-f57d1.firebaseapp.com',
    storageBucket: 'chat-app-f57d1.firebasestorage.app',
    measurementId: 'G-M6BNL4QRJG',
  );

}